---
title: "mi primer tablero"
author: "FVB"
date: "2019"
output:
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "enRdados", href: "http://www.enrdados.net", align: right }
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
```

# pag 1

## columna 1

### Gráfica temporal


```{r}
plot.ts(Nile, col="blue",
     main="Caudales en el Nilo",
     xlab="Fecha",
     ylab="Caudal m3/s")

```

> grafica de caudales en el río Nilo

## columna 2

### Gráfica estadística

```{r}
hist(Nile, col="blue",
     main="Caudales en el Nilo",
     xlab="Caudal m3/s",
     ylab="Frecuencia")

```

> grafica de frecuencias de caudales en el río Nilo

# pag 2

## ResumenDatos {data-width=250}

Los iconos los puedes buscar aqui:

 - [Font Awesome](https://fortawesome.github.io/Font-Awesome/icons/)
 - [Ionicons](http://ionicons.com/)
 - [Bootstrap Glyphicons](https://getbootstrap.com/components/#glyphicons)

### maximo caudal

```{r}
maxC<-max(Nile)
valueBox(maxC, icon = "fa-stream")

```

### Minimo caudal
```{r}
minC<-min(Nile)
valueBox(minC, icon = "fa-water")

```

### Media

```{r}
resumen<-summary(Nile)
gauge(as.numeric(resumen[4]), min = 0, max = 2000, symbol = 'm', gaugeSectors(
  success = c(0, 400), warning = c(401, 1000), danger = c(1001, 2000)
))
```

## columna 1

### Tabla de datos

Estos son los datos de caudal del río Nilo

```{r}
  summary(Nile)
  serieN<-data.frame(caudal=as.matrix(Nile), fecha=time(Nile))
  serieN
#maxC<-max(Nile)
#minC<-min(Nile)

```

