---
title: "mi primer tablero"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

# pag 1

## columna 1

### Caudales máximos anuales
```{r}
plot.ts(Nile, col="blue",
     main="Caudales max históricos en el Nilo",
     xlab="Fecha",
     ylab="Caudal m3/s")

```

> grafica de caudales maximos anuales en el río Nilo

## columna 2

### Gráfica estadística

```{r}
#histograma
hist(Nile, col="skyblue",
     main="Caudales en el Nilo",
     xlab="Caudal m3/s",
     ylab="Frecuencia")
rug(Nile) # marcas
```

> grafica de frecuencias de caudales en el río Nilo

### Boxplot

```{r}

boxplot(Nile, col="red",
        horizontal=TRUE,
        xlab="caudales maximos del Nilo")
rug(Nile) # añado marcas
```

> Variable caudal max anual

# pag 2

## columna 1

### Tabla de datos

Estos son los datos de caudal del río *Nilo*:

```{r}
  # Resumen
  summary(Nile)
  # creo una data.frame para poner fecha y caudal
  serieN<-data.frame(caudal=as.matrix(Nile), fecha=time(Nile))
  #serieN
  knitr::kable(serieN)
```

