---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
library(rhandsontable)
DF = data.frame(int = 1:100,
                numeric = rnorm(10),
                logical = TRUE,
                character = LETTERS[1:10],
                fact = factor(letters[1:10]),
                date = seq(from = Sys.Date(), by = "days", length.out = 10),
                stringsAsFactors = FALSE)

# add a sparkline chart
#DF$chart = sapply(1:10, function(x) jsonlite::toJSON(list(values=rnorm(10))))

output$tb1 = renderRHandsontable({
  rhandsontable(DF, width = 600,height = 250) %>%  hot_rows(rowHeights = 50, fixedRowsTop = 1)
})

rHandsontableOutput("tb1") 

#renderDT(                                                   
#rhandsontable(DF)
              #, rowHeaders = NULL) 
#  %>%  hot_col("chart", renderer = htmlwidgets::JS("renderSparkline"))
#)

```

### Chart C

```{r}

```

